name: Docker CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: cursofundamentosacr2026.azurecr.io
  IMAGE: websiteplatzi

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build docker image
      run: |
        docker build --platform linux/amd64 -t $REGISTRY/$IMAGE:latest -t $REGISTRY/$IMAGE:${{ github.sha }} -f CI/dockerfile CI
    - name: Publish docker image
      run: |
        docker push --all-tags $REGISTRY/$IMAGE
